services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
     image: "jaymenorca/configserver:d2"
     container_name: configserver-ms
     ports: 
     - "8072:8072"
     depends_on: 
       rabbit:
         condition: service_healthy
     healthcheck:
       test: "curl --fail --silent localhost:8072/actuator/health/readiness | grep UP || exit 1"
       interval: 10s
       timeout: 5s
       retries: 10
       start_period: 10s
     extends:
       file: common-config.yml
       service: microservice-base-config
       
  accounts:
     image: "jaymenorca/accounts:d2"
     container_name: accounts-ms
     ports: 
     - "8082:8082"
     depends_on: 
       configserver:
         condition: service_healthy
     environment:
       SPRING_APPLICATION_NAME: "accounts"
     extends:
       file: common-config.yml
       service: microservice-configserver-config

  loans:
     image: "jaymenorca/loans:d2"
     container_name: loans-ms
     ports: 
     - "8092:8092"
     depends_on: 
       configserver:
         condition: service_healthy
     environment:
       SPRING_APPLICATION_NAME: "loans"
     extends:
       file: common-config.yml
       service: microservice-configserver-config

  cards:
     image: "jaymenorca/cards:d2"
     container_name: cards-ms
     ports: 
     - "8102:8102"
     depends_on: 
       configserver:
         condition: service_healthy
     environment:
       SPRING_APPLICATION_NAME: "cards"
     extends:
       file: common-config.yml
       service: microservice-configserver-config
       
networks:
  jaymenorca:
    driver: "bridge"
