services:
#uncomment for mysql
#  accountsdb:
#    container_name: accountsdb
#    ports:
#    - 3306:3306
#    environment:
#      MYSQL_DATABASE: accountsdb
#    extends:
#      file: common-config.yml
#      service: microservice-db-config
   
#  loansdb:
#    container_name: loansdb
#    ports:
#    - 3307:3306
#    environment:
#      MYSQL_DATABASE: loansdb
#    extends:
#      file: common-config.yml
#      service: microservice-db-config

#  cardsdb:
#    container_name: cardsdb
#    ports:
#    - 3308:3306
#    environment:
#      MYSQL_DATABASE: cardsdb
#    extends:
#      file: common-config.yml
#      service: microservice-db-config
       
  configserver:
     image: "jaymenorca/configserver:v4h2"
     container_name: configserver-ms
     ports:
     - "8072:8072"
     healthcheck:
       test: "curl --fail --silent http://localhost:8072/actuator/health/readiness | grep UP || exit 1"
       interval: 15s
       timeout: 30s
       retries: 10
       start_period: 10s
     extends:
       file: common-config.yml
       service: microservice-base-config

  eurekaserver:
     image: "jaymenorca/eurekaserver:v4h2"
     container_name: eurekaserver-ms
     ports:
     - "8070:8070"
     healthcheck:
       test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit 1"
       interval: 15s
       timeout: 30s
       retries: 10
       start_period: 10s
     extends:
       file: common-config.yml
       service: microservice-configserver-config
     depends_on:
       configserver:
         condition: service_healthy
     environment:
       SPRING_APPLICATION_NAME: "eurekaserver"
       
  accounts:
     image: "jaymenorca/accounts:v4h2"
     container_name: accounts-ms
     ports: 
     - "8082:8082"
     depends_on:
#       accountsdb:
#         condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy 
     environment:
       SPRING_APPLICATION_NAME: "accounts"
#       SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
     extends:
       file: common-config.yml
       service: microservice-eureka-config

  loans:
     image: "jaymenorca/loans:v4h2"
     container_name: loans-ms
     ports: 
     - "8092:8092"
     depends_on: 
 #      loansdb:
 #        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy 
     environment:
       SPRING_APPLICATION_NAME: "loans"
#       SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
     extends:
       file: common-config.yml
       service: microservice-eureka-config

  cards:
     image: "jaymenorca/cards:v4h2"
     container_name: cards-ms
     ports: 
     - "8102:8102"
     depends_on: 
  #     cardsdb:
  #       condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy 
     environment:
       SPRING_APPLICATION_NAME: "cards"
 #      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
     extends:
       file: common-config.yml
       service: microservice-eureka-config
       
networks:
  jaymenorca:
    driver: "bridge"
